apiVersion: v2
name: kubeclustersnap
description: Helm Chart for KubeClusterSnap V2 — Ephemeral Environment IDP & Observability Platform
type: application
version: 2.3.0
appVersion: 2.3.0
keywords:
  - kubernetes
  - internal-developer-platform
  - observability
  - ephemeral-environments
  - telemetry
maintainers:
  - name: Anil Gottapu
    email: anilkumargottapu9@gmail.com
