---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeclustersnap-backend
  namespace: prod
  labels:
    app: kubeclustersnap-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubeclustersnap-backend
  template:
    metadata:
      labels:
        app: kubeclustersnap-backend
    spec:
      serviceAccountName: kubeclustersnap-sa
      containers:
        - name: backend
          image: kubeclustersnap-backend:v2.4.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: KUBECLUSTERSNAP_LICENSE_KEY
              value: "KCS-ENT-PROD-3648F75762ED"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi

---
apiVersion: v1
kind: Service
metadata:
  name: kubeclustersnap-backend-svc
  namespace: prod
spec:
  type: NodePort
  selector:
    app: kubeclustersnap-backend
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30800
